sudo: false
language: python
cache:
    directories:
        - ${HOME}/gcloud/

env:
  globals:
    - PATH=${PATH}:${HOME}/gcloud/google-cloud-sdk/bin
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_17852db5d881_key -iv $encrypted_17852db5d881_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/gcloud/google-cloud-sdk ]; then
          mkdir -p ${HOME}/gcloud &&
          wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=${HOME}/gcloud &&
          cd ${HOME}/gcloud &&
          tar xzf google-cloud-sdk.tar.gz &&
          ./google-cloud-sdk/install.sh --usage-reporting false --path-update false --command-completion false &&
          cd ${TRAVIS_BUILD_DIR};
      fi
- gcloud -q components update app
- tar -xzf credentials.tar.gz
- mkdir -p lib
# - if [ -a client-secret.json ]; then
#     gcloud auth activate-service-account --key-file client-secret.json;
#   fi
- gcloud auth activate-service-account --key-file client-secret.json;
install:
- gcloud config set project continuous-deployment--144517
- gcloud -q components update gae-python
- pip install -r requirements.txt -t lib/

script:
# - python test_main.py
# - gcloud -q preview app deploy app.yaml --promote
# - gcloud -q app deploy app.yaml --promote
- gcloud -q app deploy --project continuous-deployment--144517 --version=py app.yaml
# - python e2e_test.py
